prettier/plugin-ruby

README.md
Just adding a few extra notes on how to get prettier-ruby running.
There might be a nicer way, but this is how I was able to get it to work :+1:
=> Add additional running details

.github/ISSUE_TEMPLATE/formatting.md
Just adding a quick issue template to help out :+1:
=> Add issue template

CHANGELOG.md, src/nodes.js
=> Handle next use case

CHANGELOG.md, src/nodes.js, test/__snapshots__/ruby.test.js.snap, test/if.rb
=> Support the not operator properly

README.md
Prettier should be run over rake files too, let's update the example CLI snippet :+1:
=> Add rake file extension to read me

CHANGELOG.md, src/ripper.rb, test/__snapshots__/ruby.test.js.snap, test/comments.rb
=> Handle comments inside if, unless, and when nodes

CHANGELOG.md, src/parse.js, src/ripper.rb
=> Pass the code to be formatted over stdin

.github/ISSUE_TEMPLATE/formatting.md, CHANGELOG.md, src/ripper.rb, test/__snapshots__/ruby.test.js.snap, test/comments.rb
=> Fix up Ruby 2.5 inline comment on command

CHANGELOG.md, src/nodes.js, test/__snapshots__/ruby.test.js.snap, test/super.rb
=> Allow explicitly passing no arguments to super

src/nodes/regexp.js, test/__snapshots__/ruby.test.js.snap
=> Fix missing regex flags

CHANGELOG.md, src/nodes/params.js, test/__snapshots__/ruby.test.js.snap, test/cases/method.rb
=> Split up method args

CHANGELOG.md, src/nodes.js, test/__snapshots__/ruby.test.js.snap, test/cases/method.rb
=> Handle trailing commas with block args

CHANGELOG.md, test/__snapshots__/ruby.test.js.snap, test/cases/binary.rb, test/ruby.test.js
A part of https://github.com/prettier/plugin-ruby/issues/120
=> Switch over binary fixture to minitest

src/ripper.rb
Let's run Prettier on our ripper file.
As part of my Gem PR I'll be enforcing that this file passes prettier's rules, I just want to get this in as a pre-requisite PR :+1:
=> Run prettier on ripper

src/escapePattern.js, src/nodes/strings.js, test/__snapshots__/ruby.test.js.snap, test/cases/strings.rb, test/ruby.test.js
=> Escape patterns

CHANGELOG.md, src/nodes.js, test/__snapshots__/ruby.test.js.snap, test/cases/class.rb
=> Handle cases with empty class and module declarations that need to break

CHANGELOG.md, src/nodes.js, test/__snapshots__/ruby.test.js.snap, test/cases/lambda.rb
Closes https://github.com/prettier/plugin-ruby/issues/133.
=> Support inline lambdas better on commands

test/__snapshots__/ruby.test.js.snap, test/cases/kwargs.rb, test/ruby.test.js
Converting kwargs into minitest for #120
=> Add minitest for kwargs

test/__snapshots__/ruby.test.js.snap, test/cases/numbers.rb, test/ruby.test.js
Converting numbers into minitest for #120
=> Add minitest for numbers

src/nodes/regexp.js, src/utils.js, test/__snapshots__/ruby.test.js.snap, test/cases/regexp.rb
Closes #154 
We might need some extra tests for other complex scenarios, but the code change doesn't break the existing tests.
=> Fix regex whitespace issue

CHANGELOG.md, src/nodes.js, test/__snapshots__/ruby.test.js.snap, test/cases/next.rb, test/ruby.test.js
=> Fix up spaces between next arguments

CHANGELOG.md, src/nodes.js, src/nodes/conditionals.js, test/__snapshots__/ruby.test.js.snap, test/cases/if.rb
=> Better support for multi-line conditional predicate

CHANGELOG.md, src/nodes.js, test/__snapshots__/ruby.test.js.snap, test/cases/method.rb
=> Properly support trailing commas with and without blocks

CHANGELOG.md, src/ripper.rb, test/__snapshots__/ruby.test.js.snap, test/cases/array.rb
=> Array literal comments

src/nodes.js, test/__snapshots__/ruby.test.js.snap, test/cases/class.rb
=> Allow multiple undefs

src/nodes.js, test/__snapshots__/ruby.test.js.snap, test/cases/blocks.rb, test/cases/lambda.rb
=> Remove line breaks within block and lambda params

CHANGELOG.md, package.json, src/nodes.js, src/nodes/arrays.js, src/nodes/blocks.js, src/nodes/conditionals.js, src/nodes/methods.js, src/nodes/regexp.js, src/nodes/strings.js, test/testRunner.js
In order to support older version of node
=> Remove the spread operator

CHANGELOG.md, src/ripper.rb
=> Check earlier for invalid ruby versions

CHANGELOG.md, src/ruby.js
Fixes https://github.com/prettier/plugin-ruby/issues/233
=> Support explicit ruby interpreter

CHANGELOG.md, src/nodes.js, src/ripper.rb, test/js/hash.test.js
=> Fix up dynamic string hash keys

CHANGELOG.md, src/nodes/commands.js, src/utils.js, test/js/method.test.js
=> Better alignment for command calls

CHANGELOG.md, src/nodes/blocks.js, src/utils.js, test/js/blocks.test.js
=> Switch to curly braces if necessary for blocks

CHANGELOG.md, src/ripper.rb, test.rb, test/js/method.test.js
=> Automatically convert to def/rescue

CHANGELOG.md, src/ripper.rb, test/js/lambda.test.js
=> Support for lambda literals

CHANGELOG.md, src/nodes/commands.js, test/js/method.test.js
=> Fix up command inside def with just block arg

CHANGELOG.md, src/ripper.rb, test/js/array.test.js
=> Array references with comments

CHANGELOG.md, src/ripper.rb, test/js/blocks.test.js
=> do...end comments

CHANGELOG.md, src/ruby.js
=> Enable cursor-offset

.all-contributorsrc, CHANGELOG.md, README.md, src/nodes/calls.js, src/nodes/conditionals.js, test/js/conditionals.test.js
=> Add parens on ternary operators when needed

.all-contributorsrc, README.md, src/ripper.rb, test/js/layout.test.js
=> Multiple newlines at end

CHANGELOG.md, src/nodes/conditionals.js, test/js/conditionals.test.js
=> Handle assignment in conditional predicate

.all-contributorsrc, CHANGELOG.md, README.md, src/nodes/strings.js, test/js/strings.test.js
=> Fix xstring newlines

.all-contributorsrc, README.md, src/ripper.rb, test/js/errors.test.js
=> Always bail out

.all-contributorsrc, CHANGELOG.md, README.md, src/nodes/loops.js, test/js/while.test.js
=> Handle while and until loops modifying begin nodes

CHANGELOG.md, src/nodes/args.js, src/nodes/calls.js, test/js/blocks.test.js
=> Fix to_proc transform within aref

.all-contributorsrc, CHANGELOG.md, README.md, src/nodes/flow.js, test/js/return.test.js
=> Return breaks

CHANGELOG.md, src/nodes/strings.js, test/js/strings.test.js
=> Properly handle unnecessary double quote escapes

CHANGELOG.md, src/nodes/conditionals.js, src/nodes/loops.js, src/ripper.rb, test/js/conditionals.test.js, test/js/loops.test.js
=> Align conditional and loop predicates

.all-contributorsrc, CHANGELOG.md, README.md, src/nodes/hashes.js, test/js/hash.test.js
=> Invalid hash labels

.all-contributorsrc, .travis.yml, CHANGELOG.md, README.md, bin/ci-install, src/nodes/strings.js, test/js/strings.test.js
=> Better formatting on xstring literals

CHANGELOG.md, src/nodes/conditionals.js, src/nodes/loops.js, src/utils.js, test/js/loops.test.js
=> Fixes for assignments in predicates

CHANGELOG.md, src/ripper.rb, test/js/comments.test.js
Closes #406. Yeah @AlanFoster I agree I'm not wild about the formatting after this but at least it fixes the crash.
=> Fixes for ignored_nl

.all-contributorsrc, .prettierignore, CHANGELOG.md, README.md, src/nodes/strings.js, test/js/strings.test.js
=> Handle proper %q string escaping

.all-contributorsrc, CHANGELOG.md, README.md, src/nodes/conditionals.js, test/js/conditionals.test.js
=> Low prec ternaries

CHANGELOG.md, src/nodes/massign.js, src/ripper.rb, test/js/assign.test.js
=> Better support for trailing commas in massign

.all-contributorsrc, CHANGELOG.md, README.md, src/nodes/commands.js, test/js/method.test.js
=> Rspec `not_to` alignment

CHANGELOG.md, src/nodes/args.js, src/nodes/blocks.js, src/nodes/params.js, src/ripper.rb, test/js/blocks.test.js, test/js/method.test.js, test/rb/metadata_test.rb
=> Handle Ruby 2.7 syntax

CHANGELOG.md, src/haml/nodes/silentScript.js, src/haml/nodes/tag.js, test/js/haml/silentScript.test.js, test/js/haml/tag.test.js
=> HAML fixes

CHANGELOG.md, src/nodes/blocks.js, test/js/blocks.test.js
=> Properly maintain braces

CHANGELOG.md, src/haml/nodes/tag.js, test/js/haml/tag.test.js
=> Handle dynamic attributes on div tags

CHANGELOG.md, src/haml/nodes/tag.js, src/haml/parse.rb, test/js/haml/tag.test.js
=> Fix extra spacing in HAML

CHANGELOG.md, src/nodes/calls.js, test/js/strings.test.js
=> Handle calls with heredoc receivers

CHANGELOG.md, src/nodes/return.js
=> Handle returns with low operator precedence

test/js/parser.rb, test/js/setupTests.js
@johnschoeman can you check if this branch fixes the spawn problem? Also can you post your ruby version/node version in here? Would really like to get this fixed but I'm flying blind since they're exiting on my machine.
=> Ensure parser processes are killed in test runs

.all-contributorsrc, CHANGELOG.md, README.md, src/nodes/conditionals.js, test/js/conditionals.test.js
=> Assignment in predicate ternary

CHANGELOG.md, src/nodes/calls.js, test/js/strings.test.js
=> Fix heredocs indenting

CHANGELOG.md, src/nodes/flow.js, src/nodes/hashes.js, src/utils.js, test/js/break.test.js, test/js/next.test.js
=> Explicilty handle break and next parens

.all-contributorsrc, CHANGELOG.md, README.md, src/nodes/conditionals.js, src/nodes/loops.js, src/utils/inlineEnsureParens.js, test/js/conditionals.test.js, test/js/loops.test.js
=> Modifier parens

.all-contributorsrc, CHANGELOG.md, README.md, src/nodes/args.js, test/js/args.test.js
=> Heredocs and blocks

.all-contributorsrc, CHANGELOG.md, README.md, src/nodes/conditionals.js, test/js/conditionals.test.js
=> Ensure parent broken on multiline

src/nodes/conditionals.js, src/nodes/patterns.js, src/parser.rb, src/printer.js, test/js/nodes.test.js, test/js/patterns.test.js, test/js/setupTests.js
=> pattern matching syntax

src/nodes/calls.js, test/js/calls.test.js
=> Better handling for method chains

src/printer.js
=> Fix plain rescues with comments

src/parser.rb
=> Fix for Ruby 2.5.1 dyna symbols

src/parser.rb, test/js/comments.test.js
=> Declaration comments

src/nodes/methods.js, src/nodes/statements.js, src/parser.rb, test/js/rescue.test.js
=> Fix up ensure in bodystmt

CHANGELOG.md, prettier.gemspec, src/embed.js, src/nodes/arrays.js, src/nodes/calls.js, src/nodes/heredocs.js, src/nodes/hooks.js, src/nodes/loops.js, src/nodes/operators.js, src/nodes/regexp.js, src/nodes/rescue.js, src/nodes/strings.js, src/parser.rb, src/printer.js, src/utils.js, test/js/alias.test.js, test/js/arrays.test.js, test/js/binary.test.js, test/js/break.test.js, test/js/calls.test.js, test/js/conditionals.test.js, test/js/heredocs.test.js, test/js/loops.test.js, test/js/ranges.test.js, test/js/regexp.test.js, test/js/rescue.test.js, test/js/strings.test.js
=> Various fixes

CHANGELOG.md, src/nodes/args.js, src/nodes/calls.js, src/nodes/lambdas.js, src/nodes/params.js, src/nodes/statements.js, src/parser.rb
=> Add `method_add_block` to the potential like of method calls that can be chained.

CHANGELOG.md, src/nodes/arrays.js, src/nodes/hashes.js, src/nodes/statements.js, src/utils.js, src/utils/printEmptyCollection.js, test/js/arrays.test.js, test/js/hashes.test.js
=> Handle empty collection leading comments

.all-contributorsrc, CHANGELOG.md, README.md, src/nodes/calls.js, test/js/nodes/calls.test.js
=> Special call syntax

.all-contributorsrc, CHANGELOG.md, README.md, src/nodes/loops.js, test/js/nodes/blocks.test.js
=> Correctly print for loops

CHANGELOG.md, src/ruby/nodes/commands.js, test/js/ruby/nodes/conditionals.test.js
=> command_call with ternary argument

README.md, prettier.gemspec, rubocop.yml
A first attempt to explain how to use RuboCop with prettier for Ruby. Needs improvement!
=> Explain use with RuboCop

CHANGELOG.md, bin/sexp, src/ruby/nodes/statements.js, src/ruby/parser.js, src/ruby/parser.rb, test/rb/metadata_test.rb
@AlanFoster this ought to do it
=> Reduce json size

README.md
=> Fix typo in README.md RuboCop section

CHANGELOG.md, src/ruby/parser.rb, test/js/ruby/nodes/unary.test.js
=> Fix for #764

CHANGELOG.md, src/rbs/parser.rb, src/ruby/nodes/hashes.js, test/js/ruby/nodes/hashes.test.js
=> Fix for #788

CHANGELOG.md, bin/print, src/ruby/nodes/arrays.js, src/ruby/nodes/commands.js, src/ruby/printer.js
=> Fix for #803

.github/workflows/main.yml, src/parser/server.rb
This avoids conflicts with users' CI systems.
Fixes #808
=> Move environment variable CI -> PLUGIN_RUBY_CI.

CHANGELOG.md, src/ruby/nodes/args.js, test/js/ruby/nodes/method.test.js
=> Fix for #812

src/haml/parser.js, src/parser/getNetcat.js, src/parser/netcat.js, src/parser/parseSync.js, src/parser/requestParse.js, src/plugin.js, src/rbs/parser.js, src/ruby/parser.js, test/js/haml/parser.test.js, test/js/rbs/parser.test.js
=> Better error handling for GNU netcat usage

CHANGELOG.md, src/ruby/nodes/args.js, test/js/ruby/nodes/method.test.js
=> Fix for #835 and #836

README.md
An extra newline got added which busted the formatting of the table
=> Fix Configuration table in README.md

CHANGELOG.md, src/rbs/parser.rb, src/rbs/printer.js, test/js/rbs/method.txt
=> Fix for #847

CHANGELOG.md, src/haml/nodes/tag.js, test/js/haml/tag.test.js
=> Fix for #850

CHANGELOG.md, src/haml/nodes/tag.js, src/haml/parser.rb
=> Fix for #849

CHANGELOG.md, src/ruby/parser.rb, test/js/ruby/nodes/heredocs.test.js
=> Fix for #810

CHANGELOG.md, src/rbs/printer.js, test/js/rbs/method.txt
=> Fix for #854

CHANGELOG.md, src/haml/parser.js, src/haml/printer.js, src/rbs/parser.js, src/rbs/printer.js, src/ruby/parser.js, src/ruby/printer.js
=> Support --insert-pragma

src/parser/parseSync.js
The current netcat-like adapter error message only covers netcat, so it took me some digging when my telnet adapter broke. This change adds the telnet error to the network adapter error check and makes the error message dynamic so the proper command is displayed if the adapter doesn't support unix sockets.
=> Made netcat error message dynamic, added telnet error to check

CHANGELOG.md, src/utils/inlineEnsureParens.js, test/js/ruby/nodes/conditionals.test.js
=> Fix for #888

CHANGELOG.md, src/ruby/nodes/calls.js, test/js/ruby/nodes/calls.test.js
=> Fix for #874

CHANGELOG.md, src/ruby/nodes/strings.js, src/ruby/parser.rb, src/utils/skipAssignIndent.js, test/js/ruby/nodes/strings.test.js
=> Fix for #904

CHANGELOG.md, src/utils/noIndent.js, test/js/ruby/nodes/calls.test.js
=> Method chains with blocks

CHANGELOG.md, src/ruby/parser.rb, test/js/ruby/nodes/blocks.test.ts
=> Fix for #958

CHANGELOG.md, src/ruby/parser.rb
=> Fix for #926

CHANGELOG.md, src/ruby/nodes/params.ts, src/ruby/nodes/statements.ts, src/ruby/parser.rb, src/ruby/printer.ts, src/types/ruby.ts, test/js/ruby/nodes/method.test.ts
=> Fix for #819

CHANGELOG.md, src/haml/printer.ts, test/js/haml/tag.test.ts
=> Fix for #895

CHANGELOG.md, src/haml/printer.ts, test/js/haml/tag.test.ts
=> Fix for #900

CHANGELOG.md, src/ruby/nodes/calls.ts, test/js/ruby/nodes/calls.test.ts
=> Fix for #929

CHANGELOG.md, src/ruby/nodes/calls.ts, test/js/ruby/nodes/calls.test.ts
=> Fix for #943

CHANGELOG.md, src/parser/parseSync.ts
This doesn't actually fix #894 but it's a better experience at least.
=> Warn about plug-n-play

src/ruby/parser.rb
It's firing for all kinds of stuff and it's really not that big of a net benefit as it gets handled by comments anyway. So just turning it off for now. This should fix #983, #984, and #988.
Fixes #983
Fixes #984
Fixes #988
=> Remove magic comment handling

.github/workflows/main.yml, .npmignore
Making sure that the smoke test I added in #995 actually does what it's supposed to.
=> PnP smoketest testing

CHANGELOG.md, src/ruby/nodes/return.ts, test/js/ruby/nodes/return.test.ts
=> Fix for #1035

CHANGELOG.md, src/ruby/nodes/commands.ts
Fixes #1028 
Still not entirely happy with this, but it's much better now at least
=> Fix for #1028

CHANGELOG.md, src/ruby/nodes/blocks.ts, test/js/ruby/nodes/blocks.test.ts
=> Fixes #1042

src/haml/parser.rb, test/js/haml/tag.test.ts
Closes #1096
I added a new test, and checked that `yarn test` and `bundle exec rake` both pass. Is there any other testing mechanism I should look into?
=> Support HAML attributes starting with @

CHANGELOG.md, src/ruby/nodes/return.ts, test/js/ruby/nodes/return.test.ts
=> Fix up `return` when nodes return arrays of docs.

.github/workflows/main.yml, README.md, src/parseSync.js, src/plugin.js, src/server.rb, test/js/globalSetup.js
=> Support passing rubyPlugins options

README.md, src/parseSync.js, src/server.rb
Closes https://github.com/prettier/plugin-ruby/issues/1227
=> Pass printwidth through to server

src/parseSync.js, src/server.rb
=> Respect tabwidth

src/parseSync.js, src/server.rb
=> Fix plugins options parsing

README.md, src/parseSync.js, src/plugin.js
=> Add back rubySingleQuote option

src/plugin.js
=> Provide better errors on missing gems

src/plugin.js
=> Make sure to read all data from response socket

README.md
Update the README to let people know about changes to using plugins with Prettier >= 3.0
=> Update README for Prettier v3
