prettier/plugin-ruby

README.md
package.json

I was running into the following syntax error:
```
~/project $ prettier --write helpers/custom_helpers.rb
/Users/meleyal/project/node_modules/prettier-plugin-ruby/src/nodes.js:5
...require("./nodes/alias"),
^^^
SyntaxError: Unexpected token ...
```
It took me a moment to realise it was the lack of object rest/spread in my node version (was using 6.x).

Specify minimum node version

---

CHANGELOG.md
src/nodes/strings.js
src/ripper.rb
test/__snapshots__/ruby.test.js.snap
test/strings.rb

Properly escape double quotes when using `preferSingleQuotes: false`.

---

src/nodes/blocks.js
test/__snapshots__/ruby.test.js.snap
test/blocks.rb

Blocks with multiple statements where the first statement is a method call on the only argument to the block were being transformed with the `to_proc` shorthand, which caused all the other statements to be removed.
```ruby
loop do |i|
i.to_s
i.next
end
```
to
```ruby
loop(&:to_s)
```
This PR requires that the call be the only statement in the block for the transformation to be applied.

Stop transforming multistatement blocks with to_proc

---

README.md

Maybe I'm missing something, but I'd expect anything related to prettier should be a dev dependency only?

Specify as a dev dependency

---

src/ripper.rb

> Unsupported ruby version (RuntimeError)
> Ruby version 2.4.1 not supported. Please upgrade to 2.5 or above. (RuntimeError)

Improve incorrect ruby version error message

---

README.md
src/nodes.js
src/nodes/arrays.js
src/ruby.js
test/__snapshots__/ruby.test.js.snap
test/config/off.json
test/config/on.json
test/config/on.yml
test/method.rb

Adds a trailingComma configuration option that defaults to false. When true, adds trailing commas to broken groups of method invocations, hash literals, and array literals.
Closes #67

Support trailing comma

---

bin/print

Updating `bin/print` to take a file path or Ruby input, aligning with the current `bin/sexp` API
```ruby
$ ./bin/print foo.txt
1 + 2 + 3
```
```ruby
./bin/print 1 + 2 + 3
1 + 2 + 3
```

Align print and sexp api

---

src/ripper.rb
test/ruby.test.js

Noticed a weird bug when playing around with the Ruby prettier playground:
Poked around for a bit and found out the Ruby code wasn't valid because of the trailing comma:
> (irb):6: syntax error, unexpected end, expecting end-of-input
This PR should hopefully catch invalid Ruby source code now 🤞

Fix the handling of invalid ruby

---

test/__snapshots__/ruby.test.js.snap
test/cases/array.rb
test/ruby.test.js

Why:
We would like for the array.rb file for the test snapshots to also be a
minitest test so that we can run the ruby tests after the prettier
formatting process an validate that arrays are syntactically correct
post formatting.
this commit:
Introduces minitest to '/test/cases/array.rb'
issue: [#120](https://github.com/prettier/plugin-ruby/issues/120)

Add minitest for array.rb

---

CHANGELOG.md
Gemfile.lock
src/nodes/strings.js
src/ripper.rb
test/cases/__snapshots__/strings.test.js.snap
test/cases/strings.rb

In the case that a string contains an escape sequence, favor whichever quote the user chose. Closes #185.

Better handle string quotes

---

CHANGELOG.md
src/nodes.js
src/nodes/calls.js
test/cases/__snapshots__/blocks.test.js.snap
test/cases/__snapshots__/strings.test.js.snap
test/cases/blocks.rb
test/cases/strings.rb

Force method calls after blocks and xstrings to hang onto the end of the previous nodes

---

README.md

plus super small wording changes

no need to `npm install` after using `npm install` to install the dependencies

---

CHANGELOG.md
src/nodes/regexp.js
src/ripper.rb

Fixes #182 
Note that I'm not actually happy about the way the output looks with this, but it's good enough for now until we refactor comment handling.

Fix regex comment crash

---

CHANGELOG.md
src/ripper.rb
test/js/lambda.test.js

Was causing the parser to fail when attempting to inspect lambda nodes.
Fixes https://github.com/prettier/plugin-ruby/pull/278

Calling `super` with a block and no args

---

.all-contributorsrc

The current configuration lead to author search links (when clicking on the emoji key under the avatar picture) like https://github.com/kddeisz/plugin-ruby/commits?author=kddeisz which link to a non existing GitHub repo (maybe previous name?). 
I fixed the `projectOwner` in `.all-contributorsrc`, which should lead to theses links being generated correctly.
PS: Thanks for including me in the list with the little contribution I added. Always nice to get notifications about this :)

fix(all-contributors): fix author search link by fixing projectOwner

---

CHANGELOG.md
src/nodes/conditionals.js
test/js/conditionals.test.js

Closes #390
```rb
def setup_security_settings!
if SecuritySettings.count == 0
end
end
```
The conditional was converted into the `if_mod` form via a call to `printSingle`
```rb
def setup_security_settings!
if SecuritySettings.count == 0
end
```
The empty body scenario is now handled explicitly:
```rb
def setup_security_settings!
if SecuritySettings.count == 0
end
end
```

Handle empty if statement gracefully

---

CHANGELOG.md
src/nodes/conditionals.js
src/nodes/loops.js
test/js/conditionals.test.js
test/js/loops.test.js

When assigning the return of an `if`, `unless`, `while`, or `until`, we need to take special care to wrap them in parentheses if they are going to use the modifier form. Fixes #410.

Fixes for assigning expressions.

---

CHANGELOG.md
CONTRIBUTING.md
bin/lex

Add `bin/lex` for viewing the tokenized result of Ripper on Ruby code.
I originally needed this functionality for: https://github.com/prettier/plugin-ruby/pull/406

Add internal lex tooling

---

.all-contributorsrc
CHANGELOG.md
README.md
src/nodes/strings.js
test/js/strings.test.js

Split up the string on newline, makes for a better experience.
Fixes #217, #394, and #398.

Better interpolation in heredocs.

---

.eslintrc.json
CHANGELOG.md
src/nodes.js
src/nodes/flow.js
src/nodes/return.js
test/js/return.test.js

When returning multiple values from a return, you need to return using an array, not parens.
Fixes #386

Fix up return node printing

---

CHANGELOG.md

It seems the closing backticks was missing for one 0.16.0 changelog example

Fix CHANGELOG.md runaway code example block

---

src/nodes/return.js
test/js/return.test.js

I took a pass at fixing for my own use.  I tried to make the minimum changes required.
| Original | Before | After |
|---- |----|----|
| `return [1, 2, 3]` | `return 1, 2, 3` | `return 1, 2, 3` |
| `return [1]` | `return 1` | `return [1]` |
| `return []`| `TypeError` | `return []`|

Fixes return node for arrays

---

src/parse.js

This PR fix https://github.com/prettier/plugin-ruby/issues/450
spawnSync maxBuffer default is 1MB. https://nodejs.org/api/child_process.html#child_process_child_process_spawnsync_command_args_options
but that buffer is not enough to output big size ruby code.

Increase spawnSync maxBuffer to 10MB

---

src/nodes/ints.js
test/js/numbers.test.js

Fixes #464 
This commit changes the amount of digits that a number must have before
it is automatically formatted with underscores.
The previous implementation would format "1024" as "1_024" which had
readability issues with dates.

Change underscore number formatting to act only on 5+ digit numbers

---

playground/ripper.rb
src/parse.js
src/ripper.rb
src/utils.rb
test/js/nodes.test.js
test/js/setupTests.js
test/rb/utils_test.rb

Loading rubygems can be a slow operation. Worse yet, the load time
performance degrades as more gems are installed on the system. Luckily,
Ruby provides a flag to fix this: `--disable-gems`.
Using this flag significantly improves performance on my machine, here
are some results.
| file                                             | lint time |
|--------------------------------------------------|-----------|
| apps/admin/application.rb                        | 215ms     |
| apps/admin/config/routes.rb                      | 165ms     |
| apps/admin/controllers/about/show.rb             | 149ms     |
| apps/admin/controllers/accounts/index.rb         | 147ms     |
| apps/admin/controllers/authentication_helpers.rb | 151ms     |
| apps/admin/controllers/deployments/index.rb      | 148ms     | …

Improve perf by using --disable-gems

---

src/nodes/calls.js

for code
```
Config::Download.new('rubocop-config-prettier', filename: 'rubocop.yml', url: 'https://raw.githubusercontent.com/xinminlabs/rubocop-config-prettier/master/config/rubocop.yml').perform
```
it was converted to
```
Config::Download.new(
'rubocop-config-prettier',
filename: 'rubocop.yml',
url:
'https://raw.githubusercontent.com/xinminlabs/rubocop-config-prettier/master/config/rubocop.yml'
)
.perform
```
now, it is converted to
```
Config::Download.new(
'rubocop-config-prettier',
filename: 'rubocop.yml',
url:
'https://raw.githubusercontent.com/xinminlabs/rubocop-config-prettier/master/config/rubocop.yml'
).perform
```

wrap call name with group

---

bin/debug_print_doc

the `debug_print_doc` command returns the debug print doc, like
```
[
group([
group(["Config", "::", "Download", indent([softline, ".", "new"])]),
group([
"(",
indent([
softline,
"'",
"rubocop-config-prettier",
"'",
",",
line,
group([group(["filename:", indent([line, "'", "rubocop.yml", "'"])])])
]),
softline,
")"
]),
indent([softline, ".", "perform"])
]),
hardline,
breakParent
];
```
it helps to check internal behaviors.

add debug_print_doc command

---

src/nodes/loops.js
test/js/loops.test.js

Should print correctly. Fixes #454

`while` and `until` nodes with empty bodies

---

CHANGELOG.md
src/nodes/operators.js

it converted code from
```
['1111111111111111111111111111111111111111111111111111111111111111111111111', 222] + [1]
```
to 
```
[
'1111111111111111111111111111111111111111111111111111111111111111111111111',
222
] +
[1]
```
but it should be transformed to
```
[
'1111111111111111111111111111111111111111111111111111111111111111111111111',
222
] + [1]
```

optimize operators parser

---

src/ruby.js
test/js/files.test.js
test/js/setupTests.js

Enables haml formatting with VS Code Prettier

add haml vscode language id

---

src/nodes.js
src/nodes/methods.js
src/nodes/super.js
src/ripper.rb
test/js/super.test.js

Summary:
This work ensures inline comments are attached after the 'super' and
'zsuper' nodes.

comment handling for 'super' and 'zsuper'

---

src/ripper.rb
src/ruby.js
test/js/undef.test.js

Ensure comments are supported by the undef node

Handle comments for 'undef'

---

CHANGELOG.md
src/nodes/rescue.js
test/js/rescue.test.js

@kddeisz I went ahead and updated the Changelog though I wasn't sure if that's expected of contributors or it's something you do yourself. Maybe we should update the Contribution guidelines with a section covering specific steps to take besides code updates when submitting a PR (e.g. updating changelog - changes, profile link, all contributors, etc).
Closes #549

Do not add an empty line after `rescue` when the block is empty

---

src/nodes/arrays.js
test/js/array.test.js

Fixes a bug where non-space whitespace characters in arrays will be converted to word arrays without proper escaping. This prevents the conversion to word arrays for `\t`, `\n`, and `\r`, in addition to the existing check for spaces.
Previously, this:
```ruby
DELIMITERS = [";", "\t", "|", ","]
```
Converted to 
```ruby
DELIMITERS = %w[; \t | ,] 
```
But with this change, remains an explicit array with only quote conversion:
```ruby
DELIMITERS = [';', "\t", '|', ',']
```

Skip word-array transformations for other types of whitespace

---

playground/ripper.rb
src/ripper.rb

On ruby versions < 2.5.0 it currently fails with:
```
NameError: undefined local variable or method `current_version' for main:Object
```
instead of printing the error message:
```
Ruby version 2.4.10 not supported. Please upgrade to 2.5.0 or above.
```

define required_version and current_version for error message

---

src/parse.js

This should fix https://github.com/prettier/plugin-ruby/issues/621.
It seems passing `env` to `spawnSync` overwrites the whole ENV instead of adding the variables given. Although I'm not sure that is really what is happening, since it is working on my Mac when I run it locally. But this snippet fixes the problem when running inside a Docker container.

Don't overwrite ENV when spawning ruby process

---

CHANGELOG.md
playground/ripper.rb
src/nodes/lambdas.js
src/ripper.rb
test/js/lambda.test.js
test/rb/metadata_test.rb

Technically it's breaking the semantics of the program. Also because lambda method call arguments can't handle everything that stabby lambda can. Closes #651.

Don't convert between `lambda {}` and `-> {}`.

---

CHANGELOG.md
src/nodes/hashes.js

Closes #545
Previously, printing this:
```ruby
patch '/api/v1/shops', params: { shop: { name: 'Single Lane', category: 'food_and_drinks' } }
```
would result in this:
```ruby
patch '/api/v1/shops',
params: {
shop: { name: 'Single Lane', category: 'food_and_drinks' }
}
```
even if trailing commas was enabled. This is incorrect, as the third
line should have a trailing comma on it. The issue is that we were
attempting to handle trailing commas too low in the tree (from within
the assoclist_from_args node printing as opposed to the hash printing).

Trailing commas in hash arguments

---

src/nodes/conditionals.js
test/js/conditionals.test.js

Fixes a bug where method calls as conditions can change program behavior when converted to ternary shorthand.
For example, this
```ruby
if a.foo? bar
1
else
2
end
```
used to change to
```ruby
a.foo? bar ? 1 : 2 
a.foo?(bar ? 1 : 2)
```
but now remains unchanged with this PR.
To be honest, I'd prefer to have the above example change to
```ruby
a.foo?(bar) ? 1 : 2 
```
But I couldn't figure out how to properly organize that without some crazy traversal in `conditionals.js`, which doesn't seem sustainable. Regardless, this PR now prevents AST changes that we ran into.

Prevent ternary conversions with calls

---

src/nodes/arrays.js
src/nodes/calls.js
src/nodes/hashes.js
src/nodes/strings.js
src/parser.rb
src/utils.js

Previously there was kind of a weird dance where heredocs were either actual `heredoc` nodes (which represented squiggly heredocs) or they were `string_literal` nodes with an immediate child of `heredoc` (which represented straight-line heredocs). Now there's just one kind, which drastically simplifies what's going on.

Better heredoc handling

---

CHANGELOG.md
src/nodes/calls.js
test/js/calls.test.js

Transforms
```ruby
posts.active.where('created_at > ?', 1.year.ago).order('id asc').limit(10)
```
to
```ruby
posts
.active
.where('created_at > ?', 1.year.ago)
.order('id asc')
.limit(10)
```
Closes #63. Supersedes #488. 
All credit to @flyerhzm here, this is just a rebased and slightly more performant version of his great work.

Print method chains

---

src/nodes/commands.js
test/js/method.test.js

Closes https://github.com/prettier/plugin-ruby/issues/590
Fixes an issue where ternary to `if/else` statement conversions can cause syntax errors if they were the first argument of a method call.
If we hit that case, this change adds parentheses to the method arguments, and indents arguments one level to match formatting of other method calls with parentheses.
For example,
```ruby
foo bar ? loooooooooooooooooooooooooooooong1 : loooooooooooooooooooooooooooong2
```
becomes
```ruby
foo(
if bar
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
else
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
end
)
```

Fix ternary -> if conditional with method call

---

CHANGELOG.md
src/nodes/conditionals.js
src/utils.js
test/js/conditionals.test.js
test/js/parser.rb

A rebased version of #654
Fixes #591

Maintain parse order during if/unless modifier expressions

---

src/nodes/args.js
test/js/blocks.test.js

It solves some cases when simple argument hit 80 chars like
```
thereisamethodcall(arg1, arg2).thereisanothermethodcall(arg1, arg2).asimpleone(arg)
```
was converted to
```
thereisamethodcall(arg1, arg2).thereisanothermethodcall(arg1, arg2).asimpleone(
arg
)
```
but it would be better to be
```
thereisamethodcall(arg1, arg2).thereisanothermethodcall(arg1, arg2)
.asimpleone(arg)
```
It will cause a special case, it won't transform code when there is only one long method with only one simple argument
```
hereisalonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglongmethod(arg)
```
but I rarely see developers write such code, the change worths it, what do you think?

do not wrap line inside arg_paren for some cases

---

CHANGELOG.md
src/nodes/operators.js
src/parser.rb
test/js/conditionals.test.js

Ensure `not` keeps parentheses if they are being used.

---

src/nodes/calls.js
test/js/calls.test.js
test/js/lambda.test.js

@kddeisz let me know what you think. Moved the respective tests to `calls.test.js` to match the file which is responsible for this logic.
Closes #702

Respect original call syntax

---

src/nodes/regexp.js
src/parser.rb
test/js/nodes/regexp.test.js
test/rb/metadata_test.rb

I found some edge cases when regexp literal body has braces.
`%r(a{b/c)` this regexp turns into `%r{a{b/c}` . which causes parser error. ( unterminated regexp meets end of file )
I tried to skip replacing if literal body has braces. 
--
another solution: Escape braces? ( `%r{a\{b/c}` )  but It was complicated for me.

Do not change if regexp literal body has braces

---

CHANGELOG.md
src/nodes/calls.js
test/js/nodes/calls.test.js

If you have something like
```ruby
config.action_dispatch.rescue_responses.merge!(
'ActiveRecord::ConnectionTimeoutError' => :service_unavailable,
'ActiveRecord::QueryCanceled' => :service_unavailable,
'Rack::Timeout::RequestExpiryError' => :service_unavailable,
'Rack::Timeout::RequestTimeoutError' => :service_unavailable,
'Rack::Timeout::RequestTimeoutException' => :service_unavailable,
)
```
then we want to group the args and the method chain.
Closes #729

Long method chains with args at the end

---

CHANGELOG.md

This fixes the v1.2.5 release links to GitHub profiles.
Thanks for the quick release! Amazing 😍

Add missing GitHub profile links to README.md

---

src/ruby/embed.js
src/ruby/nodes/heredocs.js
src/utils.js
src/utils/literalLineNoBreak.js
src/utils/literallineWithoutBreakParent.js

[`hardlineWithoutBreakParent` and `literallineWithoutBreakParent`](https://github.com/prettier/prettier/blob/main/commands.md#hardlinewithoutbreakparent-and-literallinewithoutbreakparent) have been added to `prettier.doc.builders` and will be available in the next release. For consistency, this PR renames `literalLineNoBreak` in this project to `literallineWithoutBreakParent`.

Rename literalLineNoBreak to literallineWithoutBreakParent

---

CHANGELOG.md
rubocop.yml

I noticed that [`Style/Lambda` cop from RuboCop](https://docs.rubocop.org/rubocop/1.8/cops_style.html#stylelambda) has a chance on conflicting with the way `@prettier/plugin-ruby` wants to format code.
Say we have this original code:
```rb
something = -> { a_very_long_line_that_needs_to_be_splitted_to_next_one_aaa_bbb }
```
After prettifying, the code will turn to this:
```rb
something = -> do
a_very_long_line_that_needs_to_be_splitted_to_next_one_aaa_bbb
end
```
However, RuboCop does not like this, and would prefer multiline lambdas to instead look like this:
```rb
something = lambda do
a_very_long_line_that_needs_to_be_splitted_to_next_one_aaa_bbb
end
```
But if I did that change, then after prettier run, the code would turn to this one:
```rb
something =
lambda { …
```

Document RuboCop's Style/Lambda should be disabled

---

CHANGELOG.md
src/haml/parser.rb
src/parser/parseSync.js
src/parser/server.rb
src/rbs/parser.rb
src/ruby/parser.rb
test/js/files.test.js
test/js/ruby/errors.test.js
test/js/setupTests.js

Fixes #814.
Before:
```
$ bin/print foo.rb
#<Thread:0x00007f804a87a240 /Users/kddeisz/Documents/projects/prettier/plugin-ruby/src/parser/server.rb:33 run> terminated with exception (report_on_exception is true):
/Users/kddeisz/Documents/projects/prettier/plugin-ruby/src/ruby/parser.rb:2037:in `on_stmts_add': undefined method `<<' for {:type=>:method_add_arg, :body=>[{:type=>:fcall, :body=>[{:type=>:@ident, :body=>"foo", :sl=>4, :el=>4, :sc=>22, :ec=>25}], :sl=>4, :el=>4, :sc=>22, :ec=>25}, {:type=>:arg_paren, :body=>[nil], :sl=>4, :sc=>25, :el=>4, :ec=>27}], :sl=>4, :sc=>22, :el=>4, :ec=>27}:Hash (NoMethodError)
Did you mean?  <
from /Users/kddeisz/Documents/projects/prettier/plugin-ruby/src/ruby/parser.rb:98:in `parse'
from /Users/kddeisz/Documents/projects/prettier/plugin-ruby/src/ruby/p …
```

Fix for #814

---

README.md

Specify how to load the rubocop rules when prettier-ruby is installed via npm

Rubocop instructions for npm package

---

README.md

- `inherit_gem` does not work with a path, errors out in Rubocop because
of the format, it needs a key and value.
- With `inherit_from` it works.

README: Update rubocop instructions

---

README.md

* call `rbprettier` instead of `prettier`
* use `bundle exec` for consistency with earlier example

Fix arguments example in README

---

yarn.lock

Reverts prettier/plugin-ruby#873 as there seems to be some issues with Prettier 2.3.0 support. That Prettier 2.3.0 PR shouldn't have been auto merged as it didn't pass the CI. See my comments in that PR for more details.

Revert "Bump prettier from 2.2.1 to 2.3.0"

---

rubocop.yml

As noted in https://github.com/prettier/plugin-ruby/issues/825, the current Rubocop overrides cause the `Style/IfUnlessModifier` cop to misfire because if `Layout/LineLength` is unset, it assumes that the line length is infinite. 
Prettier disables all `Layout/*` cops which causes the issue above. This keeps all `Layout/*` cops disabled except `Layout/LineLength`.

Re-enable `Layout/LineLength`

---

.github/workflows/automerge.yml
.github/workflows/main.yml

This PR starts where https://github.com/prettier/plugin-ruby/pull/879 ended and rewrites the Dependabot pull request automatic merging in a safe way as described in https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
I have tested that this works with https://github.com/valscion/plugin-ruby/pull/4 — the only thing I've changed to make that pull request auto-merged was this one: https://github.com/valscion/plugin-ruby/commit/a972f7eb94f64c97da8c9b64fba81fd78c21dfb1

Enable Dependabot automerge in a safe way

---

.github/workflows/main.yml

This workflow is broken as it runs the CI steps in the commit that is in the base branch, not in the commit of the pull request itself.
In addition, this PR reverts commit a10a83c6898741dc99287cec94f2bec2da7dd0c5 which changed the CI to be triggered from `pull_request` to `pull_request_target` event.
Quoting from https://securitylab.github.com/research/github-actions-preventing-pwn-requests/:
> We have also noticed a pattern that has a vulnerable intent of use, however due to misunderstanding of `pull_request_target` ends up being a broken, but not vulnerable, workflow. In these cases, repositories switched to using the `pull_request_target` trigger, but use the default values for the `actions/checkout` action
It seems that this is indeed the case that was happening in this repository …

Remove automatic merging of dependabot pull requests for now

---

README.md

I had a lot trouble getting prettier working with VS Code. Initially I was trying to use the Ruby gem, but it seems the npm library is a better choice. 
The approach I describe is based on @coisnepe's comment in https://github.com/prettier/plugin-ruby/issues/113.

Add VSCode setup instructions

---

CHANGELOG.md
src/ruby/nodes/calls.js
test/js/ruby/nodes/calls.test.js

Group together `.where.not` calls in method chains.

---

CHANGELOG.md
src/ruby/nodes/calls.js
test/js/ruby/nodes/calls.test.js

Fix for #863

---

.github/workflows/main.yml
CHANGELOG.md
prettier.gemspec

This makes sure the package.json and doc.js are present in the gem (now necessary for latest prettier). It also adds a CI step to check this in the future.
Fixes #916.

Ensure all the necessary files are in the gem

---

CHANGELOG.md
src/ruby/nodes/strings.js
test/js/globalSetup.js
test/js/ruby/nodes/strings.test.js

Ensure hash keys with dynamic symbols do not strip their quotes

---

src/ruby/nodes/conditionals.js
src/utils/containsSingleConditional.js
test/js/ruby/nodes/conditionals.test.js

With simple nested conditionals, `prettier-ruby` can end up inserting two modifier statements on the same line.  For example:
```ruby
if a
unless b
do_something
end
end
```
turns into:
```ruby
do_something unless b if a
```
This is confusing to read even if you understand the precedence order, and Rubocop has a rule specifically banning this.  This PR adds a check in the conditional printer to make it use block form if the body contains just a single conditional (in either block or modifier form).
While writing tests for this, we noticed the entire conditionals suite was skipped; not sure if this was intentional or not.  We turned it back on for testing and it does pass, so we left it on in the PR, but can re-skip if that's not desired.

Don't insert double modifiers on the same line

---

src/ruby/nodes/conditionals.js
test/js/ruby/nodes/conditionals.test.js

Fixes #922 by adding `heredoc` to the list of node types that are not allowed in ternary statements.
Ruby style guide recommends [avoiding multi-line ternaries](https://github.com/rubocop/ruby-style-guide#multi-line-ternary-operator). One could make an argument that `heredoc`s are actually one line, but it's hard to read especially when the `heredoc` is in the `if` body.

Don't allow heredocs in a ternary

---

src/utils/containsSingleConditional.js
test/js/ruby/nodes/conditionals.test.js

This is the fix for the inverse case of #933.  Currently, prettier-plugin-ruby will turn this:
```ruby
if a
b ? c : d
end
```
into this:
```ruby
b ? c : d if a
```
which Rubocop disallows, and is also pretty confusing to read IMO.  With this fix, it will consider a ternary to be a type of single-conditional and therefore use block form (which means that the first example would pass through prettier unchanged).

Use block form when there's a ternary inside a conditional

---

src/ruby/embed.ts
test/js/ruby/embed.test.ts

This fixes two separate, but related, issues in embedded language formatting for heredocs:
First: the `getCommonLeadingWhitespace` function was considering empty lines as part of the calculation.  Some editors (and possibly prettier itself?) strip trailing whitespace from lines, so an empty line in a heredoc might have zero length and therefore shouldn't be considered part of the common leading whitespace.
Second: the content of the heredoc, and the ending, are indented to the level where the heredoc starts, not the beginning of that line.  So, for example:
```ruby
do_something <<~JS
1 + 2;
JS
```
becomes:
```ruby
do_something <<~JS
1 + 2;
JS
```
It seems as if inserting a `dedent` command inside the `lineSuffix` command fixes this behavior, but I'm not totally sure I understand the …

Embedded formatter indentation fixes

---

CHANGELOG.md
src/parser/server.rb

This mirrors the way the plugin worked in v1.x where it also ignored stderr when doing this check on the Node side.
Fixes #985

Throw away stderr when testing candidate connection methods

---

.github/workflows/main.yml
src/parser/parseSync.ts

I couldn't leave it alone after #994 😁 
This PR fixes #894.  It does it in a way I don't feel great about, in terms of knowing that I'm not inadvertently breaking someone's workflow with this.  Basically, what this does is copy the Ruby files needed for the server, as well as the `getInfo.js` script, to a temporary directory. It then runs everything from that temporary directory, and once it's done, it deletes all the temporary files.
For me, this makes everything work in both regular PnP mode and unplugged PnP mode. I'm somewhat less confident that this will work for everybody out there, not that I see any reason it shouldn't, but just because it's such a big change.

Support Yarn Plug'n'Play

---

CHANGELOG.md
src/ruby/nodes/rescue.ts
test/js/ruby/nodes/rescue.test.ts

Fixes #1000.
Thanks @nbudin! The original issue is that I was being dumb with the printing and relying on a certain doc node to be returned from the children to tell what kind of node it was, when in reality I should have been checking the type. So went that way in this PR instead.

Fix for #1000

---

lib/prettier.rb

Since the change to Open3 `STDIN` is not sent to prettier, so formatting produces an empty output.
This sets the `:stdin_data` option to pass Open3 the `STDIN`.
The previous use of `system` seems to have implicitly used the parent `STDIN`.

Fix support for piping STDIN

---

src/ruby/nodes/assign.ts
src/utils/skipAssignIndent.ts
test/js/ruby/nodes/assign.test.ts

Currently there's some special handling when the rhs of an assignment is a collection literal - the newline + indentation after the `=` doesn't get added.
e.g. prettier does this:
```ruby
hash = { 
```
not this:
```ruby
hash = 
{ 
```
This PR expands this to a couple of scenarios where it probably should have been happening but wasn't:
**Operator + Assignment**
prior behavior:
```ruby
hash ||= 
{ 
```
new behavior:
```ruby
hash ||= { 
```
**Quotewords-style Collection Literal**
prior behavior:
```ruby
arr = 
%i[
thing1
thing2
]
```
new behavior:
```ruby
arr = %i[
thing1
thing2
]
```
I think there's a case to be made that _non_-collection literals should work similarly (regexes and dynamic symbols already do) but that seems like less of an easy win.

More consistent assignment indentation

---

.github/workflows/main.yml
src/rbs/parser.rb
src/rbs/printer.ts
src/types/rbs.ts
test/js/rbs/rbs.test.ts
test/rb/rbs_test.rb
test/rb/test_helper.rb

Adds support for:
- Bounded type parameters
- Some ast changes made as part of rbs 2
Didn't add support for inline visibility modifiers b/c https://github.com/ruby/rbs/pull/923
Would be easy to monkeypatch though.

Support rbs 2.x under ruby 3.1

---

prettier.gemspec
test/js/ruby/nodes/patterns.test.js
test/js/ruby/nodes/strings.test.js

Fixes some tests that were failing on main due to changes in `syntax_tree`.
- Split a bunch of patterns out into their own tests where the content is different.
- Updates a test that is no longer escaping quotes where it used to.
- Bumps `syntax_tree` dependency to `>= 2.7.1`

Fix some tests failing on main

---

lib/prettier.rb

Resolves #1246
This PR only passes the `:stdin_data` option if `STDIN` is not attached to a terminal.
Related to #1134 (See https://github.com/prettier/plugin-ruby/pull/1134#issuecomment-1133354264)

Resolves process waiting on STDIN

---

rubocop.yml

Disable the single- vs double-quotes rules in `rubocop.yml`

---

lib/prettier/rake/task.rb

While I understand there may be value to printing out the contents of the files being parsed, I think that running the rake task in check mode if write is disabled is a more sensible mode of operation. This allows me to write a rake task for running prettier in CI.

Run Rake task in check mode if write disabled

---

README.md
src/parseSync.js
src/plugin.js

Feels like the whole point of `prettier` is that 1 `.prettierrc` sets the config for the whole project. So, to me, it's a little weird that the ruby plugin has different options to the standard package
Couldn't find any tests for single quotes or trailing commas in the codebase, and not 100% sure where they should go, so happy to add some if you point me to where.
Closes #1239

add back support for standard prettier config options

---

src/parseSync.js

When using `nvm` it seems that `spawnSync` can't find the node binary and the commands just fail awkwardly (`spawnSync` doesn't let us know it couldn't find the command). 
Related to https://github.com/prettier/plugin-ruby/issues/113

Use process.execPath instead of "node"

---

src/server.rb

👋 Hey, thanks for this plugin. 
Right now this plugin requires you to install the dependencies for formatting haml and rbs files, even if your codebase isn't using those types of files. This PR modifies `src/server.rb` so these formatting dependencies are ~~only required "on demand" - e.g., when the server is actually processing a haml or rbs file~~ only required optionally.
This change will mean we can drop `haml` as a dependency in our codebase, since it's only being imported so that we can format ruby files with this plugin.

Make haml/rbs dependencies optional

---

.github/workflows/main.yml
README.md
package.json
src/plugin.js
src/server.rb
test/js/ruby/nodes/lambda.test.js
yarn.lock

The plugin currently only works, if in shimmed environment (e.g. rbenv / asdf) the global ruby version it the same as within the project. If global ruby version is something like 2.7.0 it fails within vscode format on save.
This is due to starting the ruby interpreter (spawn) within drives root folder, which falls back to global ruby version instead of project used one.
The fix sets the working dir for spawned ruby process to the directory, where the file to be formatted is contained.
This will automatically use the correct shimmed ruby version of the project or falls back (if no shim has been used) to global ruby version.
This also may make the .editorconfig obsolete.

Support shimmed ruby versions
